SPL-StandardPHPLibrary: FilterIterator Class Reference
FilterIterator Class Reference
Public Member Functions
__call ($func, $params)
__construct (Iterator $it)
accept ()
current ()
getInnerIterator ()
key ()
next ()
rewind ()
valid ()
Protected Member Functions
__clone ()
fetch ()
Private Attributes
$it
Detailed Description
Abstract filter for iterators.
Author
Marcus Boerger
Version
1.1
Since
PHP 5.0
Instances of this class act as a filter around iterators. In other words you can put an iterator into the constructor and the instance will only return selected (accepted) elements.
The only thing that needs to be done to make this work is implementing method accept(). Typically this invloves reading the current element or key of the inner Iterator and checking whether it is acceptable.
Definition at line 26 of file filteriterator.inc.
Constructor & Destructor Documentation
FilterIterator::__construct (Iterator $it)
Constructs a filter around another iterator.
Parameters
it Iterator to filter
Definition at line 35 of file filteriterator.inc.
References $it.
{
         $this->it = $it;
     }
Member Function Documentation
FilterIterator::__call ($func, $params)
Aggregate the inner iterator.
Parameters
func Name of method to invoke
params Array of parameters to pass to method
Definition at line 121 of file filteriterator.inc.
     {
         return call_user_func_array(array($this->it, $func), $params);
     }
FilterIterator::__clone () protected
hidden __clone
Definition at line 104 of file filteriterator.inc.
{
         // disallow clone
     }
FilterIterator::accept () abstract
Accept function to decide whether an element of the inner iterator should be accessible through the Filteriterator.
Returns
whether or not to expose the current element of the inner iterator.
Referenced by fetch().
FilterIterator::current ()
Returns
The current value
Implements Iterator.
Definition at line 97 of file filteriterator.inc.
Referenced by RegexFindFile\accept(), and FindFile\accept().
{
         return $this->it->current();
     }
FilterIterator::fetch () protected
Fetch next element and store it.
Returns
void
Definition at line 61 of file filteriterator.inc.
References accept().
Referenced by next(), and rewind().
{
         while ($this->it->valid()) {
             if ($this->accept()) {
                 return;
             }
             $this->it->next();
         };
     }
FilterIterator::getInnerIterator ()
Returns
The inner iterator
Implements OuterIterator.
Definition at line 111 of file filteriterator.inc.
References $it.
Referenced by SearchIterator\__call(), DirectoryFilterDots\accept(), KeyFilter\accept(), RecursiveRegexIterator\getChildren(), RecursiveFilterIterator\getChildren(), RecursiveRegexIterator\hasChildren(), RecursiveFilterIterator\hasChildren(), and DirectoryFilterDots\key().
     {
         return $this->it;
     }
FilterIterator::key ()
Returns
The current key
Implements Iterator.
Definition at line 90 of file filteriterator.inc.
Referenced by KeyFilter\accept().
                    {
         return $this->it->key();
     }
FilterIterator::next ()
Move to next element.
Returns
void
Implements Iterator.
Definition at line 75 of file filteriterator.inc.
References fetch().
                     {
         $this->it->next();
         $this->fetch();
     }
FilterIterator::rewind ()
Rewind the inner iterator.
Implements Iterator.
Definition at line 42 of file filteriterator.inc.
References fetch().
                       {
         $this->it->rewind();
         $this->fetch();
     }
FilterIterator::valid ()
Returns
Whether more elements are available
Implements Iterator.
Definition at line 83 of file filteriterator.inc.
                      {
         return $this->it->valid();
     }
Member Data Documentation
FilterIterator::$it private
Definition at line 28 of file filteriterator.inc.
Referenced by FindFile\__construct(), __construct(), and getInnerIterator().
The documentation for this class was generated from the following file:
filteriterator.inc