SPL-StandardPHPLibrary: RecursiveIteratorIterator Class Reference
RecursiveIteratorIterator Class Reference
Public Member Functions
__construct (RecursiveIterator $it, $mode=self::LEAVES_ONLY, $flags=0)
beginChildren ()
callGetChildren ()
callHasChildren ()
current ()
endChildren ()
getDepth ()
getInnerIterator ()
getSubIterator ($level=NULL)
key ()
next ()
nextElement ()
rewind ()
valid ()
Public Attributes
const CATCH_GET_CHILD = 0x00000002
const CHILD_FIRST = 2
const LEAVES_ONLY = 0
const SELF_FIRST = 1
Private Member Functions
callNextElement ($after_move)
Private Attributes
$ait = array()
$count = 0
$flags = 0
$mode = self::LEAVES_ONLY
Detailed Description
Iterates through recursive iterators.
Author
Marcus Boerger
Version
1.2
Since
PHP 5.0
The objects of this class are created by instances of RecursiveIterator. Elements of those iterators may be traversable themselves. If so these sub elements are recursed into.
Definition at line 22 of file recursiveiteratoriterator.inc.
Constructor & Destructor Documentation
RecursiveIteratorIterator::__construct (RecursiveIterator $it, $mode = self::LEAVES_ONLY, $flags = 0)
Construct from RecursiveIterator.
Parameters
it RecursiveIterator to iterate
mode Operation mode (one of):
LEAVES_ONLY only show leaves
SELF_FIRST show parents prior to their childs
CHILD_FIRST show all children prior to their parent
flags Control flags, zero or any combination of the following (since PHP 5.1).
CATCH_GET_CHILD which catches exceptions during getChildren() calls and simply jumps to the next element.
Definition at line 53 of file recursiveiteratoriterator.inc.
References $flags, $it, and $mode.
Referenced by DirectoryGraphIterator\__construct().
     {
         $this->ait[0] = $it;
         $this->mode   = $mode;
         $this->flags  = $flags;
     }
Member Function Documentation
RecursiveIteratorIterator::beginChildren ()
Called right after calling getChildren() and its rewind().
Since
PHP 5.1
Definition at line 201 of file recursiveiteratoriterator.inc.
Referenced by next().
     {
     }
RecursiveIteratorIterator::callGetChildren ()
Returns
current sub iterators current children
Since
PHP 5.1
Definition at line 193 of file recursiveiteratoriterator.inc.
References $count.
Referenced by next().
     {
         return $this->ait[$this->count]->getChildren();
     }
RecursiveIteratorIterator::callHasChildren ()
Returns
whether current sub iterators current element has children
Since
PHP 5.1
Definition at line 185 of file recursiveiteratoriterator.inc.
References $count.
Referenced by callNextElement(), and next().
     {
         return $this->ait[$this->count]->hasChildren();
     }
RecursiveIteratorIterator::callNextElement ($after_move) private
Definition at line 213 of file recursiveiteratoriterator.inc.
References callHasChildren(), nextElement(), and valid().
Referenced by next(), and rewind().
     {
         if ($this->valid())
         {
             if ($after_move)
             {
                 if (($this->mode == self::SELF_FIRST && $this->callHasChildren())
                 ||   $this->mode == self::LEAVES_ONLY)
                 $this->nextElement();
             }
             else
             {
                 $this->nextElement();
             }
         }
     }
RecursiveIteratorIterator::current ()
Returns
current element
Implements Iterator.
Definition at line 99 of file recursiveiteratoriterator.inc.
References $count, and $it.
     {
         $it = $this->ait[$this->count];
         return $it->current();
     }
RecursiveIteratorIterator::endChildren ()
Called after current child iterator is invalid and right before it gets destructed.
Since
PHP 5.1
Definition at line 209 of file recursiveiteratoriterator.inc.
Referenced by next(), rewind(), and valid().
     {
     }
RecursiveIteratorIterator::getDepth ()
Returns
Current Depth (Number of parents)
Definition at line 177 of file recursiveiteratoriterator.inc.
Referenced by DirectoryTreeIterator\current(), and RecursiveTreeIterator\getPrefix().
     {
         return $this->level;
     }
RecursiveIteratorIterator::getInnerIterator ()
Returns
The inner iterator
Implements OuterIterator.
Definition at line 170 of file recursiveiteratoriterator.inc.
References $it.
Referenced by RecursiveCompareDualIterator\areEqual(), RecursiveCompareDualIterator\areIdentical(), and RecursiveCompareDualIterator\endChildren().
     {
         return $this->it;
     }
RecursiveIteratorIterator::getSubIterator ($level = NULL)
Returns
Sub Iterator at given level or if unspecified the current sub Iterator
Definition at line 159 of file recursiveiteratoriterator.inc.
References $count.
Referenced by DirectoryTreeIterator\__call(), RecursiveTreeIterator\__call(), DirectoryTreeIterator\current(), and RecursiveTreeIterator\getPrefix().
     {
         if (is_null($level)) {
             $level = $this->count;
         }
         return @$this->ait[$level];
     }
RecursiveIteratorIterator::key ()
Returns
current key
Implements Iterator.
Definition at line 91 of file recursiveiteratoriterator.inc.
References $count, and $it.
     {
         $it = $this->ait[$this->count];
         return $it->key();
     }
RecursiveIteratorIterator::next ()
Forward to next element.
Implements Iterator.
Definition at line 107 of file recursiveiteratoriterator.inc.
References $count, $it, beginChildren(), callGetChildren(), callHasChildren(), callNextElement(), and endChildren().
     {
         while ($this->count) {
             $it = $this->ait[$this->count];
             if ($it->valid()) {
                 if (!$it->recursed && callHasChildren()) {
                     $it->recursed = true;
                     try
                     {
                         $sub = callGetChildren();
                     }
                     catch (Exception $e)
                     {
                         if (!($this->flags & self::CATCH_GET_CHILD))
{
                             throw $e;
                         }
                         $it->next();
                         continue;
                     }
                     $sub->recursed = false;
                     $sub->rewind();
                     if ($sub->valid()) {
                         $this->ait[++$this->count] = $sub;
                         if (!$sub instanceof RecursiveIterator) {
                             throw new Exception(get_class($sub).'::getChildren() must return an object that implements RecursiveIterator');
                         }
                         $this->beginChildren();
                         return;
                     }
                     unset($sub);
                 }
                 $it->next();
                 $it->recursed = false;
                 if ($it->valid()) {
                     return;
                 }
                 $it->recursed = false;
             }
             if ($this->count) {
                 unset($this->ait[$this->count--]);
                 $it = $this->ait[$this->count];
                 $this->endChildren();
                 callNextElement(false);
             }
         }
         callNextElement(true);
     }
RecursiveIteratorIterator::nextElement ()
Called when the next element is available.
Definition at line 232 of file recursiveiteratoriterator.inc.
Referenced by callNextElement().
     {
     }
RecursiveIteratorIterator::rewind ()
Rewind to top iterator as set in constructor.
Implements Iterator.
Definition at line 62 of file recursiveiteratoriterator.inc.
References callNextElement(), and endChildren().
     {
         while ($this->count) {
             unset($this->ait[$this->count--]);
             $this->endChildren();
         }
         $this->ait[0]->rewind();
         $this->ait[0]->recursed = false;
         callNextElement(true);
     }
RecursiveIteratorIterator::valid ()
Returns
whether iterator is valid
Implements Iterator.
Definition at line 75 of file recursiveiteratoriterator.inc.
References $count, $it, and endChildren().
Referenced by callNextElement().
     {
         $count = $this->count;
         while ($count) {
             $it = $this->ait[$count];
             if ($it->valid()) {
                 return true;
             }
             $count--;
             $this->endChildren();
         }
         return false;
     }
Member Data Documentation
RecursiveIteratorIterator::$ait = array() private
Definition at line 35 of file recursiveiteratoriterator.inc.
RecursiveIteratorIterator::$count = 0 private
Definition at line 36 of file recursiveiteratoriterator.inc.
Referenced by callGetChildren(), callHasChildren(), current(), getSubIterator(), key(), next(), and valid().
RecursiveIteratorIterator::$flags = 0 private
Definition at line 38 of file recursiveiteratoriterator.inc.
Referenced by __construct().
RecursiveIteratorIterator::$mode = self::LEAVES_ONLY private
Definition at line 37 of file recursiveiteratoriterator.inc.
Referenced by RecursiveTreeIterator\__construct(), and __construct().
const RecursiveIteratorIterator::CATCH_GET_CHILD = 0x00000002
Flag: Catches exceptions during getChildren() calls and simply jumps to the next element.
Definition at line 33 of file recursiveiteratoriterator.inc.
const RecursiveIteratorIterator::CHILD_FIRST = 2
Mode: Show all children prior to their parent.
Definition at line 29 of file recursiveiteratoriterator.inc.
const RecursiveIteratorIterator::LEAVES_ONLY = 0
Mode: Only show leaves.
Definition at line 25 of file recursiveiteratoriterator.inc.
const RecursiveIteratorIterator::SELF_FIRST = 1
Mode: Show parents prior to their children.
Definition at line 27 of file recursiveiteratoriterator.inc.
The documentation for this class was generated from the following file:
recursiveiteratoriterator.inc