SPL-StandardPHPLibrary: DbaReader Class Reference
DbaReader Class Reference
Example classes
Public Member Functions
__construct ($file, $handler)
__destruct ()
current ()
key ()
next ()
rewind ()
valid ()
Protected Attributes
$db = NULL
Private Member Functions
fetch_data ()
Private Attributes
$key = false
$val = false
Detailed Description
This implements a DBA Iterator.
Author
Marcus Boerger
Version
1.0
Definition at line 17 of file dbareader.inc.
Constructor & Destructor Documentation
DbaReader::__construct ($file, $handler)
Open database $file with $handler in read only mode.
Parameters
file Database file to open.
handler Handler to use for database access.
Definition at line 30 of file dbareader.inc.
{
         if (!$this->db = dba_open($file, 'r', $handler)) {
             throw new exception('Could not open file ' . $file);
         }
     }
DbaReader::__destruct ()
Close database.
Definition at line 39 of file dbareader.inc.
{
         dba_close($this->db);
     }
Member Function Documentation
DbaReader::current ()
Returns
Current data.
Implements Iterator.
Definition at line 73 of file dbareader.inc.
References $val.
{
         return $this->val;
     }
DbaReader::fetch_data () private
Fetches the current data if $key is valid.
Definition at line 64 of file dbareader.inc.
References key().
Referenced by next(), and rewind().
{
         if ($this->key !== false) {
             $this->val = dba_fetch($this->key, $this->db);
         }
     }
DbaReader::key ()
Returns
Current key.
Implements Iterator.
Definition at line 91 of file dbareader.inc.
References $key.
Referenced by fetch_data(), next(), rewind(), and valid().
                    {
         return $this->key;
     }
DbaReader::next ()
Move to next element.
Returns
void
Implements Iterator.
Definition at line 56 of file dbareader.inc.
References fetch_data(), and key().
                     {
         $this->key = dba_nextkey($this->db);
         $this->fetch_data();
     }
DbaReader::rewind ()
Rewind to first element.
Implements Iterator.
Definition at line 46 of file dbareader.inc.
References fetch_data(), and key().
                       {
         $this->key = dba_firstkey($this->db);
         $this->fetch_data();
     }
DbaReader::valid ()
Returns
Whether more elements are available.
Implements Iterator.
Definition at line 80 of file dbareader.inc.
References key().
                      {
         if ($this->db && $this->key !== false) {
             return true;
         } else {
             return false;
         }
     }
Member Data Documentation
DbaReader::$db = NULL protected
Definition at line 20 of file dbareader.inc.
DbaReader::$key = false private
Definition at line 21 of file dbareader.inc.
Referenced by key().
DbaReader::$val = false private
Definition at line 22 of file dbareader.inc.
Referenced by current().
The documentation for this class was generated from the following file:
dbareader.inc