SPL-StandardPHPLibrary: class_tree.php File Reference
class_tree.php File Reference
Example classes
Classes
class SubClasses
Variables
$it = new RecursiveTreeIterator(new SubClasses($argv[1], true))
Detailed Description
Class Tree example.
Author
Marcus Boerger
Date
2003 - 2008
Version
1.1
Usage: php class_tree.php <class>
Simply specify the root class or interface to tree with parameter <class>.
Definition in file class_tree.php.
Variable Documentation
$it = new RecursiveTreeIterator(new SubClasses($argv[1], true))
Definition at line 105 of file class_tree.php.
Referenced by RecursiveIteratorIterator\__construct(), DualIterator\compareIterators(), RecursiveIteratorIterator\current(), RecursiveIteratorIterator\getInnerIterator(), RecursiveIteratorIterator\key(), RecursiveIteratorIterator\next(), and RecursiveIteratorIterator\valid().