SPL-StandardPHPLibrary: SplObjectStorage Class Reference
SplObjectStorage Class Reference
Public Member Functions
attach ($obj, $inf=NULL)
contains ($obj)
count ()
current ()
detach ($obj)
getInfo ()
key ()
next ()
offsetEsists ($obj)
offsetExists ($offset)
offsetGet ($obj)
offsetSet ($obj, $inf)
offsetUnset ($obj)
rewind ()
setInfo ($inf=NULL)
valid ()
Private Attributes
$index = 0
$storage = array()
Detailed Description
Object storage.
Author
Marcus Boerger
Version
1.1
Since
PHP 5.1.2
This container allows to store objects uniquly without the need to compare them one by one. This is only possible internally. The code representation here therefore has a complexity of O(n) while the actual implementation has complexity O(1).
Definition at line 23 of file splobjectstorage.inc.
Member Function Documentation
SplObjectStorage::attach ($obj, $inf = NULL)
Parameters
$obj new object to attach to storage or object whose associative information is to be replaced
$inf associative information stored along the object
Definition at line 113 of file splobjectstorage.inc.
References contains().
Referenced by offsetSet().
     {
         if (is_object($obj) && !$this->contains($obj))
         {
             $this->storage[] = array($obj, $inf);
         }
     }
SplObjectStorage::contains ($obj)
Parameters
$obj object to look for
Returns
whether $obj is contained in storage
Definition at line 94 of file splobjectstorage.inc.
Referenced by attach(), and offsetEsists().
     {
         if (is_object($obj))
         {
             foreach($this->storage as $element)
             {
                 if ($object === $element[0])
                 {
                     return true;
                 }
             }
         }
         return false;
     }
SplObjectStorage::count ()
Returns
number of objects in storage
Implements Countable.
Definition at line 86 of file splobjectstorage.inc.
     {
         return count($this->storage);
     }
SplObjectStorage::current ()
Returns
current object
Implements Iterator.
Definition at line 51 of file splobjectstorage.inc.
Referenced by getInfo().
     {
         $element = current($this->storage);
         return $element ? $element[0] : NULL
     }
SplObjectStorage::detach ($obj)
Parameters
$obj object to remove from storage
Definition at line 123 of file splobjectstorage.inc.
References rewind().
Referenced by offsetUnset().
     {
         if (is_object($obj))
         {
             foreach($this->storage as $idx => $element)
             {
                 if ($object === $element[0])
                 {
                     unset($this->storage[$idx]);
                     $this->rewind();
                     return;
                 }
             }
         }
     }
SplObjectStorage::getInfo ()
Returns
get current object's associated information
Since
5.3.0
Definition at line 60 of file splobjectstorage.inc.
References current().
     {
         $element = current($this->storage);
         return $element ? $element[1] : NULL
     }
SplObjectStorage::key ()
Returns
current key
Implements Iterator.
Definition at line 44 of file splobjectstorage.inc.
References $index.
Referenced by valid().
     {
         return $this->index;
     }
SplObjectStorage::next ()
Forward to next element.
Implements Iterator.
Definition at line 78 of file splobjectstorage.inc.
     {
         next($this->storage);
         $this->index++;
     }
SplObjectStorage::offsetEsists ($obj)
Parameters
$obj object to look for
Returns
whether $obj is contained in storage
Definition at line 182 of file splobjectstorage.inc.
References contains().
     {
         return $this->contains($obj);
     }
ArrayAccess::offsetExists ($offset) inherited
Parameters
$offset to check
Returns
whether the offset exists.
Implemented in ArrayIterator, ArrayObject, SplDoublyLinkedList, and DbaArray.
SplObjectStorage::offsetGet ($obj)
Parameters
$obj Exising object to look for
Returns
associative information stored with object
Exceptions
UnexpectedValueException if Object $obj is not contained in storage
Since
5.3.0
Implements ArrayAccess.
Definition at line 155 of file splobjectstorage.inc.
     {
         if (is_object($obj))
         {
             foreach($this->storage as $idx => $element)
             {
                 if ($object === $element[0])
                 {
                     return $element[1];
                 }
             }
         }
         throw new UnexpectedValueException('Object not found');
     }
SplObjectStorage::offsetSet ($obj, $inf)
Parameters
$obj new object to attach to storage or object whose associative information is to be replaced
$inf associative information stored along the object
Since
5.3.0
Implements ArrayAccess.
Definition at line 144 of file splobjectstorage.inc.
References attach().
     {
         $this->attach($obj, $inf);
     }
SplObjectStorage::offsetUnset ($obj)
Parameters
$obj Exising object to look for
Returns
associative information stored with object
Since
5.3.0
Implements ArrayAccess.
Definition at line 174 of file splobjectstorage.inc.
References detach().
     {
         $this->detach($obj);
     }
SplObjectStorage::rewind ()
Rewind to top iterator as set in constructor.
Implements Iterator.
Definition at line 30 of file splobjectstorage.inc.
Referenced by detach().
     {
         rewind($this->storage);
     }
SplObjectStorage::setInfo ($inf = NULL)
Returns
set current object's associated information
Since
5.3.0
Definition at line 69 of file splobjectstorage.inc.
References $index, and valid().
     {
         if ($this->valid()) {
             $this->storage[$this->index][1] = $inf;
         }
     }
SplObjectStorage::valid ()
Returns
whether iterator is valid
Implements Iterator.
Definition at line 37 of file splobjectstorage.inc.
References key().
Referenced by setInfo().
     {
         return key($this->storage) !== false;
     }
Member Data Documentation
SplObjectStorage::$index = 0 private
Definition at line 26 of file splobjectstorage.inc.
Referenced by key(), and setInfo().
SplObjectStorage::$storage = array() private
Definition at line 25 of file splobjectstorage.inc.
The documentation for this class was generated from the following file:
splobjectstorage.inc