SPL-StandardPHPLibrary: ArrayIterator Class Reference
ArrayIterator Class Reference
Internal classes
Public Member Functions
__construct ($array, $flags=0)
append ($value)
asort ()
count ()
current ()
getArrayCopy ()
getFlags ()
key ()
ksort ()
natcasesort ()
natsort ()
next ()
offsetExists ($index)
offsetGet ($index)
offsetSet ($index, $newval)
offsetUnset ($index)
rewind ()
seek ($position)
setFlags ($flags)
uasort (mixed cmp_function)
uksort (mixed cmp_function)
valid ()
Public Attributes
const ARRAY_AS_PROPS = 0x00000002
const STD_PROP_LIST = 0x00000001
Detailed Description
An Array iterator.
Since
PHP 5.0
Version
1.2
This iterator allows to unset and modify values and keys while iterating over Arrays and Objects.
When you want to iterate over the same array multiple times you need to instanciate ArrayObject and let it create ArrayIterator instances that refer to it either by using foreach or by calling its getIterator() method manually.
Definition at line 741 of file spl.php.
Constructor & Destructor Documentation
ArrayIterator::__construct ($array, $flags = 0)
Construct a new array iterator from anything that has a hash table.
That is any Array or Object.
Parameters
$array the array to use.
$flags see setFlags().
Definition at line 755 of file spl.php.
 {}
Member Function Documentation
ArrayIterator::append ($value)
Parameters
$value is appended as last element
Warning
this method cannot be called when the ArrayIterator refers to an object.
Definition at line 818 of file spl.php.
 {}
ArrayIterator::asort ()
Sort the entries by values.
Definition at line 773 of file spl.php.
 {}
ArrayIterator::count ()
Returns
the number of elements in the array or the number of public properties in the object.
Implements Countable.
Definition at line 834 of file spl.php.
 {}
ArrayIterator::current ()
Return the current element.
Implements Iterator.
Definition at line 843 of file spl.php.
Referenced by RecursiveArrayIterator\getChildren(), and RecursiveArrayIterator\hasChildren().
 {}
ArrayIterator::getArrayCopy ()
Returns
a copy of the array
Note
when the ArrayIterator refers to an object then this method returns an array of the public properties.
Definition at line 824 of file spl.php.
 {}
ArrayIterator::getFlags ()
Returns
current flags
Definition at line 769 of file spl.php.
 {}
ArrayIterator::key ()
Return the key of the current element.
Implements Iterator.
Definition at line 846 of file spl.php.
 {}
ArrayIterator::ksort ()
Sort the entries by key.
Definition at line 777 of file spl.php.
 {}
ArrayIterator::natcasesort ()
Sort the entries by values using case insensitive "natural order" algorithm.
Definition at line 793 of file spl.php.
Referenced by SubClasses\current().
 {}
ArrayIterator::natsort ()
Sort the entries by values using "natural order" algorithm.
Definition at line 789 of file spl.php.
 {}
ArrayIterator::next ()
Move forward to next element.
Implements Iterator.
Definition at line 849 of file spl.php.
 {}
ArrayIterator::offsetExists ($index)
Parameters
$index offset to inspect
Returns
whetehr offset $index esists
Implements ArrayAccess.
Definition at line 798 of file spl.php.
 {}
ArrayIterator::offsetGet ($index)
Parameters
$index offset to return value for
Returns
value at offset $index
Implements ArrayAccess.
Definition at line 803 of file spl.php.
 {}
ArrayIterator::offsetSet ($index, $newval)
Parameters
$index index to set
$newval new value to store at offset $index
Implements ArrayAccess.
Definition at line 808 of file spl.php.
Referenced by SubClasses\__construct().
 {}
ArrayIterator::offsetUnset ($index)
Parameters
$index offset to unset
Implements ArrayAccess.
Definition at line 812 of file spl.php.
 {}
ArrayIterator::rewind ()
Rewind the Iterator to the first element.
Implements Iterator.
Definition at line 837 of file spl.php.
 {}
ArrayIterator::seek ($position)
Parameters
$position offset to seek to
Exceptions
OutOfBoundsException if $position is invalid
Implements SeekableIterator.
Definition at line 829 of file spl.php.
 {}
ArrayIterator::setFlags ($flags)
Set behavior flags.
Parameters
$flags bitmask as follows: 0 set: properties of the object have their normal functionality when accessed as list (var_dump, foreach, etc.) 1 set: array indices can be accessed as properties in read/write
Definition at line 764 of file spl.php.
 {}
ArrayIterator::uasort (mixed cmp_function)
Sort the entries by values using user defined function.
Definition at line 781 of file spl.php.
 {}
ArrayIterator::uksort (mixed cmp_function)
Sort the entries by key using user defined function.
Definition at line 785 of file spl.php.
Referenced by SubClasses\__construct().
 {}
ArrayIterator::valid ()
Check if there is a current element after calls to rewind() or next().
Implements Iterator.
Definition at line 840 of file spl.php.
 {}
Member Data Documentation
const ArrayIterator::ARRAY_AS_PROPS = 0x00000002
Array indices can be accessed as properties in read/write.
Definition at line 747 of file spl.php.
const ArrayIterator::STD_PROP_LIST = 0x00000001
Properties of the object have their normal functionality when accessed as list (var_dump, foreach, etc.)
Definition at line 745 of file spl.php.
The documentation for this class was generated from the following file:
spl.php