SPL-StandardPHPLibrary: FindFile Class Reference
FindFile Class Reference
Example classes
Public Member Functions
__call ($func, $params)
__construct ($path, $file)
accept ()
current ()
getInnerIterator ()
getSearch ()
key ()
next ()
rewind ()
valid ()
Protected Member Functions
__clone ()
fetch ()
Private Attributes
$file
Detailed Description
Base class to find files.
Author
Marcus Boerger
Version
1.1
Definition at line 21 of file findfile.inc.
Constructor & Destructor Documentation
FindFile::__construct ($path, $file)
Construct from path and filename.
Parameters
$path the directory to search in If path contains ';' then this parameter is split and every part of it is used as separate directory.
$file the name of the files to search fro
Definition at line 33 of file findfile.inc.
References $file, and FilterIterator\$it.
     {
         $this->file = $file;
         $list = split(PATH_SEPARATOR, $path);
         if (count($list) <= 1) {
             parent::__construct(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path)));
         } else {
             $it = new AppendIterator();
             foreach($list as $path) {
                 $it->append(new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path)));
             }
             parent::__construct($it);
         }
     }
Member Function Documentation
FilterIterator::__call ($func, $params) inherited
Aggregate the inner iterator.
Parameters
func Name of method to invoke
params Array of parameters to pass to method
Definition at line 121 of file filteriterator.inc.
     {
         return call_user_func_array(array($this->it, $func), $params);
     }
FilterIterator::__clone () protected inherited
hidden __clone
Definition at line 104 of file filteriterator.inc.
{
         // disallow clone
     }
FindFile::accept ()
Returns
whether the current file matches the given filename
Definition at line 50 of file findfile.inc.
References FilterIterator\current().
     {
         return !strcmp($this->current(), $this->file);
     }
FilterIterator::current () inherited
Returns
The current value
Implements Iterator.
Definition at line 97 of file filteriterator.inc.
Referenced by RegexFindFile\accept(), and accept().
{
         return $this->it->current();
     }
FilterIterator::fetch () protected inherited
Fetch next element and store it.
Returns
void
Definition at line 61 of file filteriterator.inc.
References FilterIterator\accept().
Referenced by FilterIterator\next(), and FilterIterator\rewind().
{
         while ($this->it->valid()) {
             if ($this->accept()) {
                 return;
             }
             $this->it->next();
         };
     }
FilterIterator::getInnerIterator () inherited
Returns
The inner iterator
Implements OuterIterator.
Definition at line 111 of file filteriterator.inc.
References FilterIterator\$it.
Referenced by SearchIterator\__call(), DirectoryFilterDots\accept(), KeyFilter\accept(), RecursiveRegexIterator\getChildren(), RecursiveFilterIterator\getChildren(), RecursiveRegexIterator\hasChildren(), RecursiveFilterIterator\hasChildren(), and DirectoryFilterDots\key().
     {
         return $this->it;
     }
FindFile::getSearch ()
Returns
the filename to search for.
Note
This may be overloaded and contain a regular expression for an extended class that uses regular expressions to search.
Definition at line 59 of file findfile.inc.
References $file.
Referenced by RegexFindFile\accept().
     {
         return $this->file;
     }
FilterIterator::key () inherited
Returns
The current key
Implements Iterator.
Definition at line 90 of file filteriterator.inc.
Referenced by KeyFilter\accept().
                    {
         return $this->it->key();
     }
FilterIterator::next () inherited
Move to next element.
Returns
void
Implements Iterator.
Definition at line 75 of file filteriterator.inc.
References FilterIterator\fetch().
                     {
         $this->it->next();
         $this->fetch();
     }
FilterIterator::rewind () inherited
Rewind the inner iterator.
Implements Iterator.
Definition at line 42 of file filteriterator.inc.
References FilterIterator\fetch().
                       {
         $this->it->rewind();
         $this->fetch();
     }
FilterIterator::valid () inherited
Returns
Whether more elements are available
Implements Iterator.
Definition at line 83 of file filteriterator.inc.
                      {
         return $this->it->valid();
     }
Member Data Documentation
FindFile::$file private
filename to find
Definition at line 24 of file findfile.inc.
Referenced by __construct(), and getSearch().
The documentation for this class was generated from the following file:
findfile.inc