SPL-StandardPHPLibrary: SearchIterator Class Reference
SearchIterator Class Reference
Example classes
Public Member Functions
__call ($func, $params)
accept ()
current ()
getInnerIterator ()
key ()
next ()
rewind ()
valid ()
Protected Member Functions
__clone ()
fetch ()
Private Attributes
$done = false
Detailed Description
Iterator to search for a specific element.
Author
Marcus Boerger
Version
1.0
This extended FilterIterator stops after finding the first acceptable value.
Definition at line 20 of file searchiterator.inc.
Member Function Documentation
SearchIterator::__call ($func, $params)
Aggregates the inner iterator.
Definition at line 52 of file searchiterator.inc.
References FilterIterator\getInnerIterator().
     {
         return call_user_func_array(array($this->getInnerIterator(), $func), $params);
     }
FilterIterator::__clone () protected inherited
hidden __clone
Definition at line 104 of file filteriterator.inc.
{
         // disallow clone
     }
FilterIterator::accept () abstract inherited
Accept function to decide whether an element of the inner iterator should be accessible through the Filteriterator.
Returns
whether or not to expose the current element of the inner iterator.
Referenced by FilterIterator\fetch().
FilterIterator::current () inherited
Returns
The current value
Implements Iterator.
Definition at line 97 of file filteriterator.inc.
Referenced by RegexFindFile\accept(), and FindFile\accept().
{
         return $this->it->current();
     }
FilterIterator::fetch () protected inherited
Fetch next element and store it.
Returns
void
Definition at line 61 of file filteriterator.inc.
References FilterIterator\accept().
Referenced by FilterIterator\next(), and FilterIterator\rewind().
{
         while ($this->it->valid()) {
             if ($this->accept()) {
                 return;
             }
             $this->it->next();
         };
     }
FilterIterator::getInnerIterator () inherited
Returns
The inner iterator
Implements OuterIterator.
Definition at line 111 of file filteriterator.inc.
References FilterIterator\$it.
Referenced by __call(), DirectoryFilterDots\accept(), KeyFilter\accept(), RecursiveRegexIterator\getChildren(), RecursiveFilterIterator\getChildren(), RecursiveRegexIterator\hasChildren(), RecursiveFilterIterator\hasChildren(), and DirectoryFilterDots\key().
     {
         return $this->it;
     }
FilterIterator::key () inherited
Returns
The current key
Implements Iterator.
Definition at line 90 of file filteriterator.inc.
Referenced by KeyFilter\accept().
                    {
         return $this->it->key();
     }
SearchIterator::next ()
Do not move forward but instead mark as finished.
Returns
void
Implements Iterator.
Definition at line 45 of file searchiterator.inc.
     {
         $this->done = true;
     }
SearchIterator::rewind ()
Rewind and reset so that it once again searches.
Returns
void
Implements Iterator.
Definition at line 28 of file searchiterator.inc.
     {
         parent::rewind();
         $this->done = false;
     }
SearchIterator::valid ()
Returns
whether the current element is valid which can only happen once per iteration.
Implements Iterator.
Definition at line 37 of file searchiterator.inc.
     {
         return !$this->done && parent::valid();
     }
Member Data Documentation
SearchIterator::$done = false private
whether an entry was found already
Definition at line 23 of file searchiterator.inc.
The documentation for this class was generated from the following file:
searchiterator.inc